apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kube-scheduler
  name: kube-scheduler
  namespace: kube-system
spec:
  ipFamily: IPv4
  ports:
  - name: https-metrics
    port: 10259
    protocol: TCP
    targetPort: 10259
  type: ClusterIP
  selector:
    component: kube-scheduler
