- name: Initialize Kubbernetes master
  hosts: master
  tasks:
  - name: Load variables
    include_vars: ./vars/default.yml

  - name: Create kubeadm directory for config
    become: yes
    file:
      path: /etc/kubeadm/
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: '0700'

  - name: Template a kubeadm config
    template:
      src: kubeadm.yml.j2
      dest: /etc/kubeadm/kubeadm.yml
      owner: ubuntu
      group: ubuntu
      mode: '0600'

  - name: Check if cluster is already provisioned
    become: yes
    shell: kubeadm config view
    # We expect this task to fail in the first run
    ignore_errors: yes
    register: kubeadm_config

  - name: Run kubeadm init
    become: yes
    shell: kubeadm init --config /etc/kubeadm/kubeadm.yml
    register: kubeadm
    when: kubeadm_config.rc != 0

  - name: Set token for join command
    set_fact:
      token: "{{ kubeadm.stdout | regex_search('token (.*\\w)', multiline=True, ignorecase=True) | regex_replace('token ') }}"
      ca_hash: "{{ kubeadm.stdout | regex_search('discovery-token-ca-cert-hash (.*\\w)', multiline=True, ignorecase=True) | regex_replace('discovery-token-ca-cert-hash ') }}"
      api_server: "{{ kubeadm.stdout | regex_search('(\\d{0,3}\\.\\d{0,3}.\\d{0,3}.\\d{0,3}:\\d{4})') }}"
    when: kubeadm_config.rc != 0

  - name: Create local information
    local_action:
      module: copy
      content: |
        api_server: "{{ api_server }}"
        ca_hash: "{{ ca_hash }}"
        token: "{{ token }}"
      dest: ./vars/kubeadm.yml
    when: kubeadm_config.rc != 0

  - name: Create .kube directory for kubeconfig
    file:
      path: /home/ubuntu/.kube
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: '0775'

  - name: Copy admin.conf to local user
    become: yes
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/ubuntu/.kube/config
      owner: ubuntu
      group: ubuntu
      mode: '0500'
      remote_src: yes

  - name: Fetch kubeconfig for local usage
    fetch:
      src: /home/ubuntu/.kube/config
      dest: ./kube.config

  - name: Copy calico config
    become: yes
    copy:
      src: calico.yaml
      dest: /home/ubuntu/calico.yaml
      owner: ubuntu
      group: ubuntu
      mode: '0500'

  - name: Install calico networking
    shell: kubectl apply -f /home/ubuntu/calico.yaml

- name: Initialize Kubernetes worker
  hosts: worker
  tasks:
  # TODO can we identify if the worker already has joined?
  - name: Load variables
    include_vars: ./vars/kubeadm.yml

  - name: Run kubeadm join
    become: yes
    shell: kubeadm join {{ api_server }} --token {{ token }} --discovery-token-ca-cert-hash {{ ca_hash }}
